<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/linearneuralnetworks/linearregression/Linear_Regression_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install d2l

In [2]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

In [3]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [4]:
def load_array(data_arrays, batch_size, is_train=True):
  dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
  if is_train:
    dataset = dataset.shuffle(buffer_size = 1000)
  dataset = dataset.batch(batch_size)
  return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.20285213, -0.09903245],
        [-1.0532751 ,  0.04103574],
        [-0.3767706 ,  1.5705936 ],
        [-1.0242809 ,  0.48947737],
        [-0.10752826,  0.20945074],
        [-2.701553  , -0.280134  ],
        [-0.34453183,  1.5977912 ],
        [ 0.29432508,  1.0109179 ],
        [ 2.4531472 ,  0.2337036 ],
        [-0.81349134, -0.9338567 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 4.953564 ],
        [ 1.9482702],
        [-1.8889053],
        [ 0.4717918],
        [ 3.264578 ],
        [-0.2562771],
        [-1.9257773],
        [ 1.3715981],
        [ 8.303971 ],
        [ 5.7395706]], dtype=float32)>)

In [9]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [10]:
loss = tf.keras.losses.MeanSquaredError()

In [11]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [13]:
num_epochs = 3
for epoch in range(num_epochs):
  for X, y in data_iter:
    with tf.GradientTape() as tape:
      l = loss(net(X, training = True), y)
    grads = tape.gradient(l, net.trainable_variables)
    trainer.apply_gradients(zip(grads, net.trainable_variables))
  l = loss(net(features), labels)
  print(f'Epoch {epoch + 1}, loss {l:f}')

Epoch 1, loss 0.000160
Epoch 2, loss 0.000095
Epoch 3, loss 0.000095


In [15]:
net.get_weights()

[array([[ 2.000217 ],
        [-3.4002903]], dtype=float32), array([4.200341], dtype=float32)]

In [17]:
print(f'True_w: {true_w}\n')
print(f'Predicted_w: {net.get_weights()[0]}\n')
print(f'True_b: {true_b}\n')
print(f'Predicted_b: {net.get_weights()[1]}')

True_w: [ 2.  -3.4]

Predicted_w: [[ 2.000217 ]
 [-3.4002903]]

True_b: 4.2

Predicted_b: [4.200341]
