<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DL-Pytorch/image_batch_processing/Neural_Network_Image_Batch_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.nn as nn

import matplotlib.pyplot as plt
import numpy as np

In [5]:
train_set = torchvision.datasets.FashionMNIST(
    root='./root',
    train = True,
    download=True,
    transform = transforms.Compose([
        transforms.ToTensor()
    ])
)


Extracting ./root/FashionMNIST/raw/train-images-idx3-ubyte.gz to ./root/FashionMNIST/raw




Extracting ./root/FashionMNIST/raw/train-labels-idx1-ubyte.gz to ./root/FashionMNIST/raw




Extracting ./root/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to ./root/FashionMNIST/raw




Extracting ./root/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to ./root/FashionMNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [6]:
data_loader = torch.utils.data.DataLoader(train_set, batch_size=10)

In [7]:
batch = next(iter(data_loader))

In [8]:
images, labels = batch

In [9]:
print(images.shape)
print(labels.shape)

torch.Size([10, 1, 28, 28])
torch.Size([10])


In [10]:
class Network(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

    self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10)

  def forward(self,t):
    t = F.relu(self.conv1(t))
    t = F.max_pool2d(t, kernel_size=2, stride=2)
        
    t = F.relu(self.conv2(t))
    t = F.max_pool2d(t, kernel_size=2, stride=2)
        
    t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
    t = F.relu(self.fc2(t))
    t = self.out(t)

    return t

In [11]:
network = Network()

In [15]:
preds = network(images)
preds.shape

torch.Size([10, 10])

In [16]:
preds

tensor([[ 9.9420e-02,  1.6020e-01, -4.3139e-02,  1.4180e-01,  1.4596e-01,
          1.2301e-02, -1.6175e-02, -1.1942e-01, -8.5287e-02,  7.4494e-03],
        [ 8.8803e-02,  1.5948e-01, -4.0075e-02,  1.3207e-01,  1.5014e-01,
          1.5896e-02, -2.5559e-02, -9.7918e-02, -8.7982e-02, -6.3284e-03],
        [ 7.1273e-02,  1.4593e-01, -5.3531e-02,  1.1895e-01,  1.4677e-01,
         -1.4180e-03,  1.3642e-04, -7.7987e-02, -8.7182e-02, -6.1443e-03],
        [ 8.0994e-02,  1.5161e-01, -4.3621e-02,  1.2553e-01,  1.4750e-01,
          3.7184e-03, -7.8825e-03, -8.8398e-02, -8.7692e-02, -6.6166e-03],
        [ 9.5981e-02,  1.5222e-01, -3.5234e-02,  1.4347e-01,  1.4841e-01,
          1.6417e-02, -2.6432e-02, -1.0707e-01, -8.0531e-02,  4.1402e-03],
        [ 8.3404e-02,  1.6681e-01, -5.3665e-02,  1.3132e-01,  1.4556e-01,
          1.8066e-02, -1.9530e-02, -1.0147e-01, -9.2013e-02, -6.2354e-03],
        [ 7.7696e-02,  1.5854e-01, -6.1467e-02,  1.2902e-01,  1.5330e-01,
          5.1344e-04, -1.7736e-0

In [17]:
preds.argmax(dim = 1)

tensor([1, 1, 4, 1, 1, 1, 1, 1, 1, 1])

In [18]:
labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [19]:
preds.argmax(dim = 1).eq(labels)

tensor([False, False, False, False, False, False, False, False, False, False])

In [24]:
def get_num_correct(preds, labels):
  return preds.argmax(dim = 1).eq(labels).sum().item()

In [25]:
get_num_correct(preds, labels)

0