<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DL-Pytorch/flatten-reshape-squeeze/Flatten_Reshape_Squeeze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
], dtype = torch.float32)

In [3]:
t.size()

torch.Size([3, 4])

In [4]:
t.shape

torch.Size([3, 4])

In [5]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [6]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [7]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [8]:
t.reshape(1,1,12)

tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]])

In [12]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [13]:
def flatten(t):
  t = t.reshape(1,-1)
  t = t.squeeze()
  return t

In [14]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [22]:
t.reshape(1,-1)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [16]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [18]:
t2 = torch.tensor([[
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
]], dtype = torch.float32)

In [19]:
t2

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])

In [20]:
t2.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [21]:
t2.reshape(1,-1)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [23]:
a1 = torch.tensor([
    [1,2],
    [3,4]
])

a2 = torch.tensor([
    [5,6],
    [7,8]
])

In [24]:
torch.cat((a1,a2), dim = 0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [25]:
torch.cat((a1,a2), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])