<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DL-Pytorch/element-wise-operation/Broadcasting_element_wise_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

# **Addition Is An Element-Wise Operation**

In [3]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [4]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [5]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [6]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [7]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [8]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [9]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [10]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [11]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

# **Broadcasting Tensors**

In [20]:
t3 = torch.tensor([
   [1,2,3],
   [4,5,6],
   [7,8,9],
   [5,7,9]
], dtype = torch.float32)
np.broadcast_to(6, t3.shape)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [41]:
t4 = torch.tensor([
  [1,2],[4,6],[8,9]
])

t5 = torch.tensor(
  [1,2])

In [42]:
t4.shape

torch.Size([3, 2])

In [43]:
t5.shape

torch.Size([2])

In [44]:
np.broadcast_to(t5.numpy(), t4.shape)

array([[1, 2],
       [1, 2],
       [1, 2]])

# **Element-Wise Comparison Operation Examples**

In [45]:
torch.tensor([1,2,3]) < torch.tensor([3,1,2])

tensor([ True, False, False])

In [46]:
t = torch.tensor([
  [0,5,5],
  [6,0,7],
  [0,8,0]
],dtype = torch.float32)

In [47]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [48]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [49]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [50]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [51]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

# **Element-Wise Operations Using Functions**

In [52]:
t.abs()

tensor([[0., 5., 5.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [53]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.2361],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [54]:
t.neg()

tensor([[-0., -5., -5.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [55]:
t.neg().abs()

tensor([[0., 5., 5.],
        [6., 0., 7.],
        [0., 8., 0.]])