<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/deep-learning-computation/Convolutions_for_images.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install d2l==0.17.0

In [ ]:
import tensorflow as tf
from d2l import tensorflow as d2l

In [ ]:
X = tf.constant([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = tf.constant([[0.0, 1.0], [2.0, 3.0]])

In [ ]:
K.shape

TensorShape([2, 2])

In [ ]:
X.shape

TensorShape([3, 3])

In [ ]:
K.shape[0]

2

In [ ]:
h, w = K.shape

In [ ]:
Y = tf.Variable(tf.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1)))
Y

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
for i in range(Y.shape[0]):
  print(i)

0
1


In [ ]:
for j in range(Y.shape[1]):
  print(j)

0
1


In [ ]:
X[0: 0 + 2, 0: 0 + 2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 1.],
       [3., 4.]], dtype=float32)>

In [ ]:
X[0: 0 + 2, 0: 0 + 2]*K

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 6., 12.]], dtype=float32)>

In [ ]:
Z0 = tf.reduce_sum(X[0: 0 + 2, 0: 0 + 2]*K)

In [ ]:
X[0: 0 + 2, 1: 1 + 2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [4., 5.]], dtype=float32)>

In [ ]:
X[0: 0 + 2, 1: 1 + 2]*K

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  2.],
       [ 8., 15.]], dtype=float32)>

In [ ]:
Z1 = tf.reduce_sum(X[0: 0 + 2, 1: 1 + 2]*K)

In [ ]:
X[1: 1 + 2, 0: 0 + 2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 7.]], dtype=float32)>

In [ ]:
X[1: 1 + 2, 0: 0 + 2]*K

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  4.],
       [12., 21.]], dtype=float32)>

In [ ]:
Z2 = tf.reduce_sum(X[1: 1 + 2, 0: 0 + 2]*K)

In [ ]:
X[1: 1 + 2, 1 : 1 + 2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 5.],
       [7., 8.]], dtype=float32)>

In [ ]:
X[1: 1 + 2, 1 : 1 + 2]*K

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  5.],
       [14., 24.]], dtype=float32)>

In [ ]:
Z3 = tf.reduce_sum(X[1: 1 + 2, 1 : 1 + 2]*K)

In [ ]:
Z = tf.Variable([[Z0, Z1],[Z2, Z3]])
Z

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[19., 25.],
       [37., 43.]], dtype=float32)>

In [ ]:
def corr2D(K, X):
  h, w = K.shape
  Y = tf.Variable(tf.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1)))
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j].assign(tf.reduce_sum(X[i: i + h, j : j + w]*K))
  return Y

In [ ]:
corr2D(K,X)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[19., 25.],
       [37., 43.]], dtype=float32)>

# **Convolutional Layers**

In [ ]:
class Conv2D(tf.keras.layers.Layer):
  def __init__(self):
    super().__init__()

  def build(self, kernel_size):
    initalizer = tf.random_normal_initializer()
    self.weight = self.add_weight(name='w', shape=kernel_size,
                                  initializer = initializer)
    self.bias = self.add_weight(name='b', shape=(1,),
                                initalizer=initializer)
  
  def call(self, inputs):
    return corr2D(inputs, self.weight) + self.bias

In [ ]:
X[:,2:6]

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(X[:,2:6].shape)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
X = tf.Variable(tf.ones((6,8)))
X[:, 2 : 6].assign(tf.zeros(X[:,2:6].shape))
X

<tf.Variable 'Variable:0' shape=(6, 8) dtype=float32, numpy=
array([[1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.]], dtype=float32)>

In [ ]:
K = tf.constant([[1.0, -1.0]])
K

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1., -1.]], dtype=float32)>

In [ ]:
Y = corr2D(K, X)
Y

<tf.Variable 'Variable:0' shape=(6, 7) dtype=float32, numpy=
array([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.]], dtype=float32)>

# **Learning a Kernel**

In [ ]:
conv2d = tf.keras.layers.Conv2D(1, (1, 2), use_bias = False)

X = tf.reshape(X, (1, 6, 8, 1))
Y = tf.reshape(Y, (1, 6, 7, 1))
lr = 3e-2

Y_hat = conv2d(X)
for i in range(10):
  with tf.GradientTape(watch_accessed_variables=False) as g:
    g.watch(conv2d.weights[0])
    Y_hat =  conv2d(X)
    l = (abs(Y_hat - Y))**2
    update = tf.multiply(lr, g.gradient(l, conv2d.weights[0]))
    weights = conv2d.get_weights()
    weights[0] = conv2d.weights[0] - update
    conv2d.set_weights(weights)
    if (i + 1) % 2 == 0:
      print(f'epoch {i + 1}, loss {tf.reduce_sum(l):.3f}')

epoch 2, loss 7.159
epoch 4, loss 2.138
epoch 6, loss 0.742
epoch 8, loss 0.282
epoch 10, loss 0.112


In [ ]:
tf.reshape(conv2d.get_weights()[0], (1, 2))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 0.9564683, -1.0246809]], dtype=float32)>