<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/deep-learning-computation/Layers_Blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
X = tf.random.uniform((2,20))

In [ ]:
print(X)

tf.Tensor(
[[0.6933     0.03762817 0.78348863 0.82843494 0.15776145 0.7898406
  0.9793494  0.16792393 0.6700556  0.42193186 0.8439832  0.27952492
  0.17298758 0.76411486 0.44233084 0.75070584 0.01135123 0.71261024
  0.96735716 0.9571028 ]
 [0.9596062  0.01836276 0.5824499  0.19470036 0.60992634 0.8447319
  0.12987566 0.9512795  0.23756373 0.11392939 0.16944504 0.20313406
  0.5526484  0.3832084  0.4634254  0.8283843  0.65831304 0.0782311
  0.38897002 0.7084359 ]], shape=(2, 20), dtype=float32)


In [ ]:
net = tf.keras.models.Sequential([
     tf.keras.layers.Dense(256, activation=tf.nn.relu),
     tf.keras.layers.Dense(10)
])

In [ ]:
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.05568464,  0.24302539,  0.06315324,  0.07059248, -0.4292512 ,
         0.4181226 , -0.13064606,  0.02337881,  0.28365898,  0.5221276 ],
       [ 0.19141117,  0.21183017,  0.07438122,  0.26406896, -0.65063375,
         0.22435659, -0.05096188, -0.01365806,  0.12954023,  0.38539147]],
      dtype=float32)>

In [ ]:
net2 = tf.keras.models.Sequential([
       tf.keras.layers.Dense(256)
])

In [ ]:
net2(X).shape

TensorShape([2, 256])

In [ ]:
net3 = tf.keras.models.Sequential([
       tf.keras.layers.Dense(10)
])

In [ ]:
net3(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-1.3295599 , -0.03291249, -1.960444  ,  0.87108755, -0.07527152,
        -0.9182358 ,  1.6118492 ,  0.04701871, -0.19393682, -1.8835232 ],
       [-1.1256139 ,  0.8081824 , -1.6470587 ,  0.49304524, -0.39516404,
        -0.7169469 ,  1.093387  , -1.0387497 , -0.01272376, -0.66822606]],
      dtype=float32)>

# **Custom Block**

In [ ]:
class MLP(tf.keras.Model):
   def __init__(self):
     super().__init__()
     self.hidden = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
     self.out = tf.keras.layers.Dense(units=10)
   def call(self, X):
     return self.out(self.hidden((X)))

In [ ]:
net = MLP()
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.22337538,  0.35913664, -0.42112973, -0.11525286,  0.04800361,
         0.00635406,  0.06781952,  0.05469295,  0.33267218, -0.29871452],
       [-0.00133211,  0.24003711, -0.43220982, -0.02137034,  0.00148057,
         0.02582267,  0.08180286,  0.02701246,  0.20420554, -0.13258053]],
      dtype=float32)>

In [ ]:
class MySequential(tf.keras.Model):
  def __init__(self, *args):
    super().__init__()
    self.modules = []
    for block in args:
      self.modules.append(block)
  def call(self, X):
    for module in self.modules:
      X = module(X)
    return X

In [ ]:
net = MySequential(
    tf.keras.layers.Dense(units=256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10)
)

In [ ]:
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.07436351,  0.17277515, -0.17010735,  0.3086537 ,  0.01758344,
         0.30682576, -0.18397468, -0.29217243,  0.20852043, -0.11587077],
       [-0.11454844,  0.04786712, -0.07589786,  0.12069547,  0.01648302,
         0.26873797, -0.13611707,  0.03153742,  0.15710506, -0.17765762]],
      dtype=float32)>

In [ ]:
class FixedHiddenMLP(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.flatten = tf.keras.layers.Flatten()
    self.rand_weight = tf.constant(tf.random.uniform((20,20)))
    self.dense = tf.keras.layers.Dense(20, activation=tf.nn.relu)
  
  def call(self,inputs):
    X = self.flatten(inputs)
    X = tf.nn.relu(tf.matmul(X, self.rand_weight) + 1)
    X = self.dense(X)
    while tf.reduce_sum(tf.math.abs(X)) > 1:
      X /= 2
    return tf.reduce_sum(X)

In [ ]:
z = tf.constant([[1,1,1], [1,1,1]])
z.numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
tf.reduce_sum(z).numpy()

6

In [ ]:
net = FixedHiddenMLP()
net(X).numpy()

0.639675