<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/deep-learning-computation/parameter_management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
net = tf.keras.models.Sequential([
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(4, activation=tf.nn.relu),
      tf.keras.layers.Dense(1)
])

X = tf.random.uniform((2,4))
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.09063291],
       [0.05431719]], dtype=float32)>

In [4]:
print(net.layers[1].weights)

[<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.02805543,  0.44287962,  0.8137488 , -0.7485931 ],
       [ 0.5900647 , -0.27857918,  0.81397015, -0.0592016 ],
       [ 0.10147846, -0.32446694,  0.6055265 , -0.31475013],
       [-0.33696538, -0.80825037,  0.5958602 , -0.7081617 ]],
      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [5]:
print(net.layers[2].weights)

[<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[ 0.1518991 ],
       [-0.8676224 ],
       [ 0.0110532 ],
       [ 0.09682751]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


In [6]:
print(net.get_weights( ))

[array([[-0.02805543,  0.44287962,  0.8137488 , -0.7485931 ],
       [ 0.5900647 , -0.27857918,  0.81397015, -0.0592016 ],
       [ 0.10147846, -0.32446694,  0.6055265 , -0.31475013],
       [-0.33696538, -0.80825037,  0.5958602 , -0.7081617 ]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[ 0.1518991 ],
       [-0.8676224 ],
       [ 0.0110532 ],
       [ 0.09682751]], dtype=float32), array([0.], dtype=float32)]
