<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/linear-algebra/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
x = tf.constant(3.0)
y = tf.constant(2.0)
x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

# **Vectors**

In [ ]:
x = tf.range(9)
print(x)
print()
print(len(x))
print()
print(x.shape)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

9

(9,)


# **Matrices**

In [ ]:
A = tf.reshape(tf.range(18), (6,3))

In [ ]:
tf.transpose(A)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]], dtype=int32)>

In [ ]:
B = tf.constant([[1,2,3], [4,5,6],[7,8,9]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])>

# **Tensors**

In [ ]:
X = tf.reshape(tf.range(24), (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [ ]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
B = A
A , A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [ ]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

# **Reduction**

In [ ]:
x = tf.range(4, dtype=tf.float32)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [ ]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))

In [ ]:
print(A.shape)
print()
print(tf.reduce_sum(A))

(5, 4)

tf.Tensor(190.0, shape=(), dtype=float32)


In [ ]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [ ]:
A_sum_axis0 = tf.reduce_sum(A, axis = 0)
print(A_sum_axis0)
print()
print(A_sum_axis0.shape)

tf.Tensor([40. 45. 50. 55.], shape=(4,), dtype=float32)

(4,)


In [ ]:
A_sum_axis1 = tf.reduce_sum(A, axis = 1)
print(A_sum_axis1)
print()
print(A_sum_axis1.shape)

tf.Tensor([ 6. 22. 38. 54. 70.], shape=(5,), dtype=float32)

(5,)


In [ ]:
tf.reduce_sum(A, axis=[0,1])

<tf.Tensor: shape=(), dtype=float32, numpy=190.0>

In [ ]:
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=float32, numpy=9.5>

In [ ]:
tf.reduce_sum(A)/tf.size(A).numpy()

<tf.Tensor: shape=(), dtype=float32, numpy=9.5>

In [ ]:
tf.reduce_mean(A, axis = 0)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

# **Non-Reduction Sum**

In [ ]:
sum_A = tf.reduce_sum(A, axis = 1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [ ]:
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [ ]:
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

In [ ]:
tf.cumsum(A, axis=1)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  3.,  6.],
       [ 4.,  9., 15., 22.],
       [ 8., 17., 27., 38.],
       [12., 25., 39., 54.],
       [16., 33., 51., 70.]], dtype=float32)>

# **Dot Product**

In [ ]:
y = tf.ones(4, dtype=tf.float32)
print(x)
print()
print(y)
print()
print(tf.tensordot(x, y, axes = 0))

tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)

tf.Tensor(
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(4, 4), dtype=float32)


# **Matrix-Vector Products**

In [ ]:
print(A)
print()
print(x)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]], shape=(5, 4), dtype=float32)

tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)


In [ ]:
tf.linalg.matvec(A,x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>

# **Matrix-Matrix Multiplication**

In [ ]:
print(A)
print()
B = tf.ones((4,3), tf.float32)
print(B)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]], shape=(5, 4), dtype=float32)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [ ]:
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>

# **Norms**

In [ ]:
u = tf.constant([-3.0,-4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [ ]:
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [ ]:
tf.ones((4,9))

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.norm(tf.ones((4,9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

# **Exercises**

# **1/ Prove that the transpose of a matrix $\mathbf{A}'s$ transpose $(\mathbf{A}^T)^T = \mathbf{A}: $**

**Solution**: We have $\mathbf{A} \Leftrightarrow \mathbf{[A]}_{ij}$ and $(\mathbf{[A]}_{ij})^T \Leftrightarrow \mathbf{[A]}_{ji} \Rightarrow (\mathbf{[A]}_{ji})^T = \mathbf{[A]}_{ij}$ then $(\mathbf{[A]}_{ji})^T \Leftrightarrow \mathbf{[A]}_{ij}.$ 

In [2]:
A = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [3]:
tf.transpose(tf.transpose(A))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

# **2/ Given two $\mathbf{A}$ and $\mathbf{B}$ show that $\mathbf{A}^T + \mathbf{B}^T = (\mathbf{A} + \mathbf{B})^T$.**

In [8]:
A = tf.constant([[1,2,3],[4,5,6]])
print(A)
B = tf.constant([[1,2,3],[4,5,6]])
print(B)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
print(A + B)
print()
print(tf.transpose(A + B))

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[ 2  8]
 [ 4 10]
 [ 6 12]], shape=(3, 2), dtype=int32)


In [12]:
print(tf.transpose(A))
print()
print(tf.transpose(B))
print()
print(tf.transpose(A) + tf.transpose(B))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[ 2  8]
 [ 4 10]
 [ 6 12]], shape=(3, 2), dtype=int32)


# **3/ Give any square matrix $\mathbf{A}$ is $\mathbf{A} + \mathbf{A}^T$ always symmetric.**

**Solution**: $\mathbf{X} = \mathbf{A} + \mathbf{A}^T$. $\mathbf{X}$ is symmetric $\Leftrightarrow \mathbf{X} = \mathbf{X}^T$ then $\mathbf{X}^T - \mathbf{X} = 0$

In [13]:
A = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(tf.transpose(A))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)


In [14]:
print(A + tf.transpose(A))
print()
print(tf.transpose(A + tf.transpose(A)) - (A + tf.transpose(A)))

tf.Tensor(
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


# **4/ We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?**

In [21]:
A = tf.reshape(tf.range(24), (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [22]:
len(A)

2

In [25]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[12, 15, 18, 21],
       [48, 51, 54, 57]], dtype=int32)>

In [27]:
tf.reduce_sum(A, axis = 2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6, 22, 38],
       [54, 70, 86]], dtype=int32)>

In [34]:
tf.reduce_sum(A,axis=0)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]], dtype=int32)>

In [35]:
B = tf.constant([[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]])
B

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [37]:
tf.linalg.diag_part(B)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>