<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DLTensorflow/data-preprocessing/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import os
import pandas as pd
import tensorflow as tf

In [5]:
os.makedirs(os.path.join("content", 'data'), exist_ok=True)
data_file = os.path.join("content", 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n')
  f.write('NA,Pave,127500\n')
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [9]:
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [15]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)
print()
print(outputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


In [16]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [19]:
X, y = tf.constant(inputs.values), tf.constant(outputs.values)
print(X)
print()
print(y)

tf.Tensor(
[[3. 1. 0.]
 [2. 0. 1.]
 [4. 0. 1.]
 [3. 0. 1.]], shape=(4, 3), dtype=float64)

tf.Tensor([127500 106000 178100 140000], shape=(4,), dtype=int64)


# **Exercises**

In [21]:
data_file_exercises = os.path.join('content','data', 'exercises.csv')
with open(data_file_exercises, 'w') as f:
  f.write('NumRooms,NumRestroom,NumKitchen,Price\n')
  f.write('2,3,2,1123123123\n')
  f.write('3,3,3,123123\n')
  f.write('NA,1,4,123123\n')
  f.write('9,NA,5,123123\n')
  f.write('NA,NA,6,1231123\n')

In [22]:
data = pd.read_csv(data_file_exercises)
print(data)

   NumRooms  NumRestroom  NumKitchen       Price
0       2.0          3.0           2  1123123123
1       3.0          3.0           3      123123
2       NaN          1.0           4      123123
3       9.0          NaN           5      123123
4       NaN          NaN           6     1231123


In [23]:
data.dropna()

NumRooms  NumRestroom  NumKitchen       Price
0       2.0          3.0           2  1123123123
1       3.0          3.0           3      123123

In [25]:
inputs, outputs = data.iloc[:, 0:3], data.iloc[:, 3]
print(inputs)
print()
print(outputs)

   NumRooms  NumRestroom  NumKitchen
0       2.0          3.0           2
1       3.0          3.0           3
2       NaN          1.0           4
3       9.0          NaN           5
4       NaN          NaN           6

0    1123123123
1        123123
2        123123
3        123123
4       1231123
Name: Price, dtype: int64


In [26]:
X, y = tf.constant(inputs.values), tf.constant(outputs.values)
print(X)
print()
print(y)

tf.Tensor(
[[ 2.  3.  2.]
 [ 3.  3.  3.]
 [nan  1.  4.]
 [ 9. nan  5.]
 [nan nan  6.]], shape=(5, 3), dtype=float64)

tf.Tensor([1123123123     123123     123123     123123    1231123], shape=(5,), dtype=int64)
