<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DL-Pytorch/argmax_reduction_tensor/ArgMax_Reduction_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t = torch.tensor([
   [0,1,0],
   [2,0,2],
   [0,3,0]
], dtype = torch.float32)

In [3]:
t.sum()

tensor(8.)

In [4]:
t.numel()

9

In [22]:
t.std()

tensor(1.1667)

In [5]:
t.sum().numel() < t.numel()

True

In [14]:
size_t = t.shape
number_of_element = size_t[0] * size_t[1]

In [15]:
sum_t = sum([sum(i) for i in t])
sum_t

tensor(8.)

In [17]:
mean_t = sum_t / number_of_element
mean_t

tensor(0.8889)

In [24]:
sum_of_squared_error = sum([sum((i - mean_t).pow(2)) for i in t])
sum_of_squared_error

tensor(10.8889)

In [26]:
std = torch.sqrt(sum_of_squared_error / (number_of_element - 1))
std

tensor(1.1667)

# **Reducing Tensors By Axes**

In [27]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [28]:
t.sum(dim = 0)

tensor([6., 6., 6., 6.])

In [29]:
t.sum(dim = 1)

tensor([ 4.,  8., 12.])

In [30]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

# **Argmax Tensor Reduction Operation**

In [31]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]    
], dtype = torch.float32)

In [32]:
t.max()

tensor(5.)

In [33]:
t.argmax()

tensor(11)

In [34]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [35]:
t.max(dim = 0)

torch.return_types.max(values=tensor([4., 3., 3., 5.]), indices=tensor([2, 1, 1, 2]))

In [36]:
t.argmax(dim = 0)

tensor([2, 1, 1, 2])

In [37]:
t.max(dim = 1)

torch.return_types.max(values=tensor([2., 3., 5.]), indices=tensor([3, 1, 3]))

In [38]:
t.argmax(dim = 1)

tensor([3, 1, 3])

# **Understanding dimensions in PyTorch**
https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be

In [39]:
y = torch.tensor([
    [
     [1,2,3],
     [4,5,6]
    ],
    [
     [1,2,3],
     [4,5,6]
    ],
    [
     [1,2,3],
     [4,5,6]
    ]
])

In [40]:
y.shape

torch.Size([3, 2, 3])

# **Dim = 0**

In [41]:
torch.sum(y, dim = 0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [42]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
y[1]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [45]:
y[2]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
y[0] + y[1] + y[2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

# **Dim = 1**

In [47]:
torch.sum(y, dim = 1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [48]:
y[0][0]

tensor([1, 2, 3])

In [51]:
y[0][1]

tensor([4, 5, 6])

In [56]:
a = y[0][0] + y[0][1]
a

tensor([5, 7, 9])

In [53]:
y[1][0]

tensor([1, 2, 3])

In [54]:
y[1][0]

tensor([1, 2, 3])

In [58]:
b = y[1][0] + y[1][1]
b

tensor([5, 7, 9])

In [59]:
y[2][0]

tensor([1, 2, 3])

In [60]:
y[2][1]

tensor([4, 5, 6])

In [62]:
c = y[2][0] + y[2][1]
c

tensor([5, 7, 9])

In [70]:
torch.stack([a,b,c], dim = 0)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

# **Dim = 2**

In [71]:
torch.sum(y, dim = 2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

In [83]:
a = torch.stack((y[0][0][0] + y[0][0][1] + y[0][0][2], y[0][1][0] + y[0][1][1] + y[0][1][2]))
a

tensor([ 6, 15])

In [84]:
b = torch.stack((y[0][0][0] + y[0][0][1] + y[0][0][2], y[0][1][0] + y[0][1][1] + y[0][1][2]))
b

tensor([ 6, 15])

In [85]:
c = torch.stack((y[0][0][0] + y[0][0][1] + y[0][0][2], y[0][1][0] + y[0][1][1] + y[0][1][2]))
c

tensor([ 6, 15])

In [86]:
torch.stack((a,b,c))

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])