<a href="https://colab.research.google.com/github/AnhVietPham/Deep-Learning/blob/main/DL-Pytorch/stack_concat/Stack_Concat_pytorch_tensorFlow_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
t1 = torch.tensor([1,1,1])
t1

tensor([1, 1, 1])

In [4]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [5]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [6]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


# **Stack Vs Cat In PyTorch**

In [7]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [8]:
print(t1.unsqueeze(dim=0))
print(t1.unsqueeze(dim=1))

tensor([[1, 1, 1]])
tensor([[1],
        [1],
        [1]])


In [9]:
torch.cat((t1,t2,t3), dim = 0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [10]:
torch.stack((t1,t2,t3), dim = 0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [11]:
torch.cat((
    t1.unsqueeze(0),
    t2.unsqueeze(0),
    t3.unsqueeze(0)
), dim = 0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [12]:
torch.stack((t1,t2,t3), dim = 1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [13]:
torch.cat((
    t1.unsqueeze(1),
    t2.unsqueeze(1),
    t3.unsqueeze(1)
), dim = 1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

# **Stack Vs Concat In TensorFlow**

In [14]:
import tensorflow as tf

In [15]:
t1 = tf.constant([1,1,1])
t2 = tf.constant([2,2,2])
t3 = tf.constant([3,3,3])

In [16]:
tf.concat((t1,t2,t3), axis = 0)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int32)>

In [17]:
tf.stack((t1,t2,t3), axis = 0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [18]:
tf.concat((
    tf.expand_dims(t1,0),
    tf.expand_dims(t2,0),
    tf.expand_dims(t3,0)
), axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [19]:
tf.stack(
    (t1,t2,t3),
    axis = 1
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [20]:
tf.concat((
    tf.expand_dims(t1,1),
    tf.expand_dims(t2,1),
    tf.expand_dims(t3,1)
), axis = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

# **Stack Vs Concatenate In NumPy**

In [21]:
import numpy as np


In [22]:
t1 = np.array([1,1,1])
t2 = np.array([2,2,2])
t3 = np.array([3,3,3])

In [23]:
np.concatenate((t1,t2,t3), axis = 0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
np.stack(
    (t1,t2,t3),
    axis = 0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [25]:
np.concatenate(
    (
        np.expand_dims(t1, 0),
        np.expand_dims(t2, 0),
        np.expand_dims(t3, 0)
    ),
    axis = 0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

# **Joining Images Into A Single Batch**

In [26]:
t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)

In [28]:
torch.stack(
    (t1,t2,t3),
    dim = 0
).shape

torch.Size([3, 3, 28, 28])

# **Joining Batches Into A Single Batch**

In [31]:
t1 = torch.zeros(1,3,28,28)
t2 = torch.zeros(1,3,28,28)
t3 = torch.zeros(1,3,28,28)

In [32]:
torch.cat(
    (t1,t2,t3),
    dim = 0
).shape

torch.Size([3, 3, 28, 28])

# **Joining Images With An Existing Batch**

In [33]:
batch = torch.zeros(3,3,28,28)
t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)

In [35]:
images_batch = torch.stack(
    (t1,t2,t3),
    dim = 0
)
images_batch.shape

torch.Size([3, 3, 28, 28])

In [38]:
torch.cat(
    (batch, images_batch),
    dim = 0
).shape

torch.Size([6, 3, 28, 28])

In [42]:
torch.cat(
    (
        batch,
        t1.unsqueeze(0),
        t2.unsqueeze(0),
        t3.unsqueeze(0)
    ), dim = 0
).shape

torch.Size([6, 3, 28, 28])